configpath: /Users/<updateme>/.oci/config
useinstanceprincipal: false
source:
  profilename: <updateme>
  bucketname:  <updateme>
  region: <updateme>
target:
  profilename: <updateme>
  bucketname: <updateme>
  region: <updateme>
home_region:
  <updateme>

batchsize: 100
limit: 2
progressinterval: 50
maxconcurrency: 10

renamer-maxworker: 50
maker-numfile: 1000000
maker-maxfilesize: 409600


deltaupdate: true
force_source_delete: false
force_source_refresh: false